
config:
  rate-limit:
    prefix: winjay
    type: redis
    array-config-enabled: false
    #rate-limit-interfaces:
    #  - {"method": "put", "uri": "/relayattack/{tenantid}/role/{roleid}", "limit": 6, "limitPeriod": 60}
    rate-limit-interface-string: '[{"method": "put", "uri": "/relayattack/{tenantid}/role/{roleid}", "limit": 8, "limitPeriod": 60}]'
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        min-idle: 2
    password: 123456
  cache:
    redis:
      key-prefix: false
